export const Fonts = {
    FredokaOne: 'FredokaOne-Regular',
    MuliExtraLight: 'Muli-ExtraLight',
    MuliLight: 'Muli-Light',
    MuliRegular: 'Muli-Regular',
    MuliSemiBold: 'Muli-SemiBold',
    MuliBold: 'Muli-Bold',
    MuliExtraBold: 'Muli-ExtraBold',
    RalewayExtraLight: 'Raleway-ExtraLight',
    RalewayLight: 'Raleway-Light',
    RalewayRegular: 'Raleway-Regular',
    RalewaySemiBold: 'Raleway-SemiBold',
    RalewayBold: 'Raleway-Bold',
    RalewayExtraBold: 'Raleway-ExtraBold',
    NunitoExtraBold: 'Nunito-ExtraBold',
}
